// File generated by FlutterFire CLI & configured for Digital Hostel Gate Pass.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2grgAOTr3NR-j67C_KKXytkWh-aTaarc',
    appId: '1:410957326255:web:5f56197722140068fbb15a',
    messagingSenderId: '410957326255',
    projectId: 'gateentry-8ef3e',
    authDomain: 'gateentry-8ef3e.firebaseapp.com',
    storageBucket: 'gateentry-8ef3e.firebasestorage.app',
    measurementId: 'G-NJ4Z7S6XN8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm9cDSeJovoa1Sb2sV30W5ZwX1mS89q3Y',
    appId: '1:410957326255:android:faa8576e08538329fbb15a',
    messagingSenderId: '410957326255',
    projectId: 'gateentry-8ef3e',
    storageBucket: 'gateentry-8ef3e.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwlWCxF8Rm0lWlS45irKjOnXyZ1NLiW_M',
    appId: '1:410957326255:ios:0af9ef4ee4f01ebefbb15a',
    messagingSenderId: '410957326255',
    projectId: 'gateentry-8ef3e',
    storageBucket: 'gateentry-8ef3e.firebasestorage.app',
    iosBundleId: 'com.hostel.gatepass.hostelGatePass',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwlWCxF8Rm0lWlS45irKjOnXyZ1NLiW_M',
    appId: '1:410957326255:ios:0af9ef4ee4f01ebefbb15a',
    messagingSenderId: '410957326255',
    projectId: 'gateentry-8ef3e',
    storageBucket: 'gateentry-8ef3e.firebasestorage.app',
    iosBundleId: 'com.hostel.gatepass.hostelGatePass',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2grgAOTr3NR-j67C_KKXytkWh-aTaarc',
    appId: '1:410957326255:web:73cf1840957a88ebfbb15a',
    messagingSenderId: '410957326255',
    projectId: 'gateentry-8ef3e',
    authDomain: 'gateentry-8ef3e.firebaseapp.com',
    storageBucket: 'gateentry-8ef3e.firebasestorage.app',
    measurementId: 'G-6G0CNY8EEN',
  );
}
